public class TenthGraderAcads implements acadsinterface {
//extends StudentAcadsAbstract {
	
    //public override Integer getTotalSubjects () { return 1;}
    //public override void setTotalSubjects () {}
    //public override Map<String,double> setSubjectMarksMap () { return new Map<String, double>();}
    //public override void calculateGPA () {}
    
    public Integer getTotalSubjects () { return 1;}
    public void setTotalSubjects () {}
    public Map<String,double> setSubjectMarksMap () { return new Map<String, double>();}
    public void calculateGPA () {}
}